name: Sphinx Build

on: [push]

jobs:  
  sphinx-build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Set up poetry
        uses: Gr1N/setup-poetry@v7
    
      - 
        name: Build docs
        run: |
          cd docs
          make html
          
      - 
        name: Deploy to pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          build_dir: docs/build/html
          jekyll: false
          verbose: true
          
